# Generated by Django 5.2.5 on 2026-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
