# Generated by Django 5.2.5 on 2026-09-19 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_association_is_maintenance_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='admin',
        ),
        migrations.AddField(
            model_name='association',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='association',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
