# Generated by Django 5.2.5 on 2026-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payer',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='payer',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
