# Generated by Django 5.2.5 on 2026-09-19 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_remove_association_admin_association_created_at_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='association.association'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin')], default='superadmin', max_length=15),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
