# Generated by Django 6.0 on 2026-02-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_provider_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference from payment provider (e.g. Ercaspay)",
                max_length=100,
                null=True,
            ),
        ),
    ]
